export interface GreIssueTopic {
  id: number;
  prompt: string;
  directions: string;
  accessCode: string;
  category?: string;
}

export const OFFICIAL_GRE_ISSUE_POOL: GreIssueTopic[] = [
  {
    id: 1,
    accessCode: 'ISSUE001',
    prompt: 'Governments should place few, if any, restrictions on scientific research and development.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Science & Government Policy',
  },
  {
    id: 2,
    accessCode: 'ISSUE002',
    prompt: 'The best way to teach is to praise positive actions and ignore negative ones.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Education & Pedagogy',
  },
  {
    id: 3,
    accessCode: 'ISSUE003',
    prompt: 'Governments should offer college and university education free of charge to all students.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Education & Public Policy',
  },
  {
    id: 4,
    accessCode: 'ISSUE004',
    prompt: 'The luxuries and conveniences of contemporary life prevent people from developing into truly strong and independent individuals.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Society & Culture',
  },
  {
    id: 5,
    accessCode: 'ISSUE005',
    prompt: 'In any field of inquiry, the beginner is more likely than the expert to make important contributions.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Expertise & Innovation',
  },
  {
    id: 6,
    accessCode: 'ISSUE006',
    prompt: 'The surest indicator of a great nation is represented not by the achievements of its rulers, artists, or scientists, but by the general welfare of its people.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Governance & Society',
  },
  {
    id: 7,
    accessCode: 'ISSUE007',
    prompt: 'The best way to teach — whether as an educator, employer, or parent — is to praise positive actions and ignore negative ones.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim. In developing and supporting your position, be sure to address the most compelling reasons and/or examples that could be used to challenge your position.',
    category: 'Education & Leadership',
  },
  {
    id: 8,
    accessCode: 'ISSUE008',
    prompt: "Teachers' salaries should be based on their students' academic performance.",
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim. In developing and supporting your position, be sure to address the most compelling reasons and/or examples that could be used to challenge your position.',
    category: 'Education & Public Policy',
  },
  {
    id: 9,
    accessCode: 'ISSUE009',
    prompt: 'Society should make efforts to save endangered species only if the potential extinction of those species is the result of human activities.',
    directions: 'Write a response in which you discuss your views on the policy and explain your reasoning for the position you take. In developing and supporting your position, you should consider the possible consequences of implementing the policy and explain how these consequences shape your position.',
    category: 'Environment & Policy',
  },
  {
    id: 10,
    accessCode: 'ISSUE010',
    prompt: 'College students should base their choice of a field of study on the availability of jobs in that field.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim. In developing and supporting your position, be sure to address the most compelling reasons and/or examples that could be used to challenge your position.',
    category: 'Higher Education & Career',
  },
  {
    id: 11,
    accessCode: 'ISSUE011',
    prompt: 'As we acquire more knowledge, things do not become more comprehensible, but more complex and mysterious.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Philosophy & Science',
  },
  {
    id: 12,
    accessCode: 'ISSUE012',
    prompt: 'In any situation, progress requires discussion among people who have contrasting points of view.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Society & Dialogue',
  },
  {
    id: 13,
    accessCode: 'ISSUE013',
    prompt: 'Educational institutions should dissuade students from pursuing fields of study in which they are unlikely to succeed.',
    directions: 'Write a response in which you discuss your views on the policy and explain your reasoning for the position you take. In developing and supporting your position, you should consider the possible consequences of implementing the policy and explain how these consequences shape your position.',
    category: 'Education & Guidance',
  },
  {
    id: 14,
    accessCode: 'ISSUE014',
    prompt: 'Governments should not fund any scientific research whose consequences are unclear.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Science & Funding',
  },
  {
    id: 15,
    accessCode: 'ISSUE015',
    prompt: 'Society should identify those children who have special talents and provide training for them at an early age to develop their talents.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Youth & Gifted Education',
  },
  {
    id: 16,
    accessCode: 'ISSUE016',
    prompt: 'It is primarily through our identification with social groups that we define ourselves.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Identity & Sociology',
  },
  {
    id: 17,
    accessCode: 'ISSUE017',
    prompt: 'College students should be encouraged to pursue subjects that interest them rather than the courses that seem most likely to lead to jobs.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Higher Education',
  },
  {
    id: 18,
    accessCode: 'ISSUE018',
    prompt: 'Claim: When planning courses, educators should take into account the interests and suggestions of their students.\nReason: Students are more motivated to learn when they are interested in what they are studying.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'Curriculum & Pedagogy',
  },
  {
    id: 19,
    accessCode: 'ISSUE019',
    prompt: 'The greatness of individuals can be decided only by those who live after them, not by their contemporaries.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'History & Greatness',
  },
  {
    id: 20,
    accessCode: 'ISSUE020',
    prompt: 'Students should always question what they are taught instead of accepting it passively.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Critical Thinking',
  },
  {
    id: 21,
    accessCode: 'ISSUE021',
    prompt: 'The increasingly rapid pace of life today causes more problems than it solves.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Modern Life & Technology',
  },
  {
    id: 22,
    accessCode: 'ISSUE022',
    prompt: 'Claim: It is no longer possible for a society to regard any living man or woman as a hero.\nReason: The reputation of anyone who is subjected to media scrutiny will eventually be diminished.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'Media & Heroes',
  },
  {
    id: 23,
    accessCode: 'ISSUE023',
    prompt: 'Competition for high grades seriously limits the quality of learning at all levels of education.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Education & Assessment',
  },
  {
    id: 24,
    accessCode: 'ISSUE024',
    prompt: "Universities should require every student to take a variety of courses outside the student's field of study.",
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Interdisciplinary Studies',
  },
  {
    id: 25,
    accessCode: 'ISSUE025',
    prompt: 'Educators should find out what students want included in the curriculum and then offer it to them.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Curriculum Design',
  },
  {
    id: 26,
    accessCode: 'ISSUE026',
    prompt: 'Educators should teach facts only after their students have studied the ideas, trends, and concepts that help explain those facts.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Instructional Strategy',
  },
  {
    id: 27,
    accessCode: 'ISSUE027',
    prompt: 'Claim: We can usually learn much more from people whose views we share than from those whose views contradict our own.\nReason: Disagreement can cause stress and inhibit learning.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'Communication & Learning',
  },
  {
    id: 28,
    accessCode: 'ISSUE028',
    prompt: 'Government officials should rely on their own judgment rather than unquestioningly carry out the will of the people they serve.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Leadership & Politics',
  },
  {
    id: 29,
    accessCode: 'ISSUE029',
    prompt: 'Young people should be encouraged to pursue long-term, realistic goals rather than seek immediate fame and recognition.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Ambition & Culture',
  },
  {
    id: 30,
    accessCode: 'ISSUE030',
    prompt: 'If a goal is worthy, then any means taken to attain it are justifiable.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Ethics & Philosophy',
  },
  {
    id: 31,
    accessCode: 'ISSUE031',
    prompt: 'In order to become well-rounded individuals, all college students should be required to take courses in which they read poetry, novels, mythology, and other types of imaginative literature.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Humanities & Education',
  },
  {
    id: 32,
    accessCode: 'ISSUE032',
    prompt: 'In order for any work of art — for example, a film, a novel, a poem, or a song — to have merit, it must be understandable to most people.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Arts & Accessibility',
  },
  {
    id: 33,
    accessCode: 'ISSUE033',
    prompt: 'Many important discoveries or creations are accidental: it is usually while seeking the answer to one question that we come across the answer to another.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Discovery & Innovation',
  },
  {
    id: 34,
    accessCode: 'ISSUE034',
    prompt: 'The main benefit of the study of history is to dispel the illusion that people living now are significantly different from people who lived in earlier times.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'History & Human Nature',
  },
  {
    id: 35,
    accessCode: 'ISSUE035',
    prompt: 'Learning is primarily a matter of personal discipline; students cannot be motivated by school or college alone.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Education & Discipline',
  },
  {
    id: 36,
    accessCode: 'ISSUE036',
    prompt: 'Scientists and other researchers should focus their research on areas that are likely to benefit the greatest number of people.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Science & Utilitarianism',
  },
  {
    id: 37,
    accessCode: 'ISSUE037',
    prompt: 'Politicians should pursue common ground and reasonable consensus rather than elusive ideals.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Politics & Governance',
  },
  {
    id: 38,
    accessCode: 'ISSUE038',
    prompt: 'People should undertake risky action only after they have carefully considered its consequences.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Risk & Decision Making',
  },
  {
    id: 39,
    accessCode: 'ISSUE039',
    prompt: 'Leaders are created by the demands that are placed on them.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Leadership & Circumstance',
  },
  {
    id: 40,
    accessCode: 'ISSUE040',
    prompt: 'There is little justification for society to make extraordinary efforts — especially at a great cost in money and jobs — to save endangered animal or plant species.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Environment & Economics',
  },
  {
    id: 41,
    accessCode: 'ISSUE041',
    prompt: 'The human mind will always be superior to machines because machines are only tools of human minds.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Artificial Intelligence & Mind',
  },
  {
    id: 42,
    accessCode: 'ISSUE042',
    prompt: 'People who are the most deeply committed to an idea or policy are also the most critical of it.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Commitment & Criticism',
  },
  {
    id: 43,
    accessCode: 'ISSUE043',
    prompt: 'Some people believe that society should try to save every plant and animal species, despite the expense to humans in effort, time, and financial well-being. Others believe that society need not make extraordinary efforts, especially at a great cost in money and jobs, to save endangered species.',
    directions: 'Write a response in which you discuss which view more closely aligns with your own position and explain your reasoning for the position you take. In developing and supporting your position, you should address both of the views presented.',
    category: 'Conservation & Human Welfare',
  },
  {
    id: 44,
    accessCode: 'ISSUE044',
    prompt: 'Some people believe that the purpose of education is to free the mind and the spirit. Others believe that formal education tends to restrain our minds and spirits rather than set them free.',
    directions: 'Write a response in which you discuss which view more closely aligns with your own position and explain your reasoning for the position you take. In developing and supporting your position, you should address both of the views presented.',
    category: 'Philosophy of Education',
  },
  {
    id: 45,
    accessCode: 'ISSUE045',
    prompt: 'Some people believe it is often necessary, even desirable, for political leaders to withhold information from the public. Others believe that the public has a right to be fully informed.',
    directions: 'Write a response in which you discuss which view more closely aligns with your own position and explain your reasoning for the position you take. In developing and supporting your position, you should address both of the views presented.',
    category: 'Government Transparency',
  },
  {
    id: 46,
    accessCode: 'ISSUE046',
    prompt: "Claim: Universities should require every student to take a variety of courses outside the student's major field of study.\nReason: Acquiring knowledge of various academic disciplines is the best way to become truly educated.",
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'Broad Education',
  },
  {
    id: 47,
    accessCode: 'ISSUE047',
    prompt: 'Knowing about the past cannot help people to make important decisions today.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'History & Relevance',
  },
  {
    id: 48,
    accessCode: 'ISSUE048',
    prompt: 'The most effective way to understand contemporary culture is to analyze the trends of its youth.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Youth Culture',
  },
  {
    id: 49,
    accessCode: 'ISSUE049',
    prompt: "People's attitudes are determined more by their immediate situation or surroundings than by society as a whole.",
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take. In developing and supporting your position, you should consider ways in which the statement might or might not hold true and explain how these considerations shape your position.',
    category: 'Psychology & Environment',
  },
  {
    id: 50,
    accessCode: 'ISSUE050',
    prompt: 'Nations should suspend government funding for the arts when significant numbers of their citizens are hungry or unemployed.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take. In developing and supporting your position, describe specific circumstances in which adopting the recommendation would or would not be advantageous and explain how these examples shape your position.',
    category: 'Arts & Social Welfare',
  },
  {
    id: 51,
    accessCode: 'ISSUE051',
    prompt: "All parents should be required to volunteer time to their children's schools.",
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take.',
    category: 'Education & Community',
  },
  {
    id: 52,
    accessCode: 'ISSUE052',
    prompt: 'Colleges and universities should require their students to spend at least one semester studying in a foreign country.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take.',
    category: 'Global Education',
  },
  {
    id: 53,
    accessCode: 'ISSUE053',
    prompt: 'Some people believe that in order to thrive, a society must put its own overall success before the well-being of its individual citizens. Others believe that the well-being of a society can only be measured by the general welfare of all its people.',
    directions: 'Write a response in which you discuss which view more closely aligns with your own position and explain your reasoning for the position you take.',
    category: 'Individual vs Collective Welfare',
  },
  {
    id: 54,
    accessCode: 'ISSUE054',
    prompt: 'Claim: Any piece of information referred to as a fact should be mistrusted, since it may well be proven false in the future.\nReason: Much of the information that people assume is factual actually turns out to be inaccurate.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'Epistemology & Facts',
  },
  {
    id: 55,
    accessCode: 'ISSUE055',
    prompt: 'Claim: Nations should suspend government funding for the arts when significant numbers of their citizens are hungry or unemployed.\nReason: It is inappropriate — and, perhaps, even cruel — to use public resources to fund the arts when people\'s basic needs are not being met.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'Resource Allocation & Arts',
  },
  {
    id: 56,
    accessCode: 'ISSUE056',
    prompt: 'Claim: Many problems of modern society cannot be solved by laws and the legal system.\nReason: Laws cannot change what is in people\'s hearts or minds.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'Legal Systems & Human Nature',
  },
  {
    id: 57,
    accessCode: 'ISSUE057',
    prompt: 'The primary goal of technological advancement should be to increase people\'s efficiency so that they have more leisure time.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take.',
    category: 'Technology & Leisure',
  },
  {
    id: 58,
    accessCode: 'ISSUE058',
    prompt: 'Educators should base their assessment of students\' learning not on students\' grasp of facts but on the ability to explain the ideas, trends, and concepts that those facts illustrate.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the recommendation and explain your reasoning for the position you take.',
    category: 'Educational Assessment',
  },
  {
    id: 59,
    accessCode: 'ISSUE059',
    prompt: 'Unfortunately, in contemporary society, creating an appealing image has become more important than the reality or truth behind that image.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement and explain your reasoning for the position you take.',
    category: 'Image vs Reality',
  },
  {
    id: 60,
    accessCode: 'ISSUE060',
    prompt: "The effectiveness of a country's leaders is best measured by examining the well-being of that country's citizens.",
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim.',
    category: 'Leadership Metrics',
  },
  {
    id: 61,
    accessCode: 'ISSUE061',
    prompt: 'A nation should require all of its students to study the same national curriculum until they enter college.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim.',
    category: 'Standardized Education',
  },
  {
    id: 62,
    accessCode: 'ISSUE062',
    prompt: 'Educational institutions should actively encourage their students to choose fields of study in which jobs are plentiful.',
    directions: 'Write a response in which you discuss your views on the policy and explain your reasoning for the position you take.',
    category: 'Career Guidance',
  },
  {
    id: 63,
    accessCode: 'ISSUE063',
    prompt: "People's behavior is largely determined by forces not of their own making.",
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim.',
    category: 'Determinism vs Free Will',
  },
  {
    id: 64,
    accessCode: 'ISSUE064',
    prompt: 'Although innovations such as video, computers, and the Internet seem to offer schools improved methods for instructing students, these technologies all too often distract from real learning.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement.',
    category: 'EdTech & Distraction',
  },
  {
    id: 65,
    accessCode: 'ISSUE065',
    prompt: 'The best ideas arise from a passionate interest in commonplace things.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement.',
    category: 'Creativity & Observation',
  },
  {
    id: 66,
    accessCode: 'ISSUE066',
    prompt: 'To be an effective leader, a public official must maintain the highest ethical and moral standards.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim.',
    category: 'Ethics & Leadership',
  },
  {
    id: 67,
    accessCode: 'ISSUE067',
    prompt: 'Claim: Imagination is a more valuable asset than experience.\nReason: People who lack experience are free to imagine what is possible without the constraints of established habits and attitudes.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'Imagination vs Experience',
  },
  {
    id: 68,
    accessCode: 'ISSUE068',
    prompt: 'In most professions and academic fields, imagination is more important than knowledge.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement.',
    category: 'Imagination vs Knowledge',
  },
  {
    id: 69,
    accessCode: 'ISSUE069',
    prompt: 'Critical judgment of work in any given field has little value unless it comes from someone who is an expert in that field.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement.',
    category: 'Expert Critique',
  },
  {
    id: 70,
    accessCode: 'ISSUE070',
    prompt: 'Some people believe that scientific discoveries have given us a much better understanding of the world around us. Others believe that science has revealed to us that the world is infinitely more complex than we ever realized.',
    directions: 'Write a response in which you discuss which view more closely aligns with your own position.',
    category: 'Science & Worldview',
  },
  {
    id: 71,
    accessCode: 'ISSUE071',
    prompt: 'In any profession — business, politics, education, government — those in power should step down after five years.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim.',
    category: 'Term Limits & Governance',
  },
  {
    id: 72,
    accessCode: 'ISSUE072',
    prompt: 'Requiring university students to take a variety of courses outside their major fields of study is the best way to ensure that students become truly educated.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement.',
    category: 'General Education',
  },
  {
    id: 73,
    accessCode: 'ISSUE073',
    prompt: 'Claim: The surest indicator of a great nation is not the achievements of its rulers, artists, or scientists.\nReason: The surest indicator of a great nation is actually the welfare of all its people.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'National Greatness',
  },
  {
    id: 74,
    accessCode: 'ISSUE074',
    prompt: 'Any leader who is quickly and easily influenced by shifts in popular opinion will accomplish little.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement.',
    category: 'Popular Opinion & Conviction',
  },
  {
    id: 75,
    accessCode: 'ISSUE075',
    prompt: "It is primarily in cities that a nation's cultural traditions are generated and preserved.",
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement.',
    category: 'Urban Culture',
  },
  {
    id: 76,
    accessCode: 'ISSUE076',
    prompt: 'When old buildings stand on ground that modern planners feel could be better used for modern purposes, modern development should be given precedence over the preservation of historic buildings.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the statement.',
    category: 'Historic Preservation vs Modernity',
  },
  {
    id: 77,
    accessCode: 'ISSUE077',
    prompt: 'Claim: The surest indicator of a great nation must be the achievements of its rulers, artists, or scientists.\nReason: Great achievements by a nation\'s rulers, artists, or scientists will ensure a good life for the majority of that nation\'s people.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'Achievements & Welfare',
  },
  {
    id: 78,
    accessCode: 'ISSUE078',
    prompt: 'The best way to understand the character of a society is to examine the character of the men and women that the society chooses as its heroes or its role models.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim.',
    category: 'Heroes & Role Models',
  },
  {
    id: 79,
    accessCode: 'ISSUE079',
    prompt: "Some people claim that a nation's government should preserve its wilderness areas in their natural state. Others argue that these areas should be developed for potential economic gain.",
    directions: 'Write a response in which you discuss which view more closely aligns with your own position.',
    category: 'Wilderness & Economic Development',
  },
  {
    id: 80,
    accessCode: 'ISSUE080',
    prompt: 'Some people argue that successful leaders in government, industry, or other fields must be highly competitive. Other people claim that in order to be successful, a leader must be willing and able to cooperate with others.',
    directions: 'Write a response in which you discuss which view more closely aligns with your own position.',
    category: 'Competition vs Cooperation',
  },
  {
    id: 81,
    accessCode: 'ISSUE081',
    prompt: 'Some people believe that corporations have a responsibility to promote the well-being of the societies and environments in which they operate. Others believe that the only responsibility of corporations, provided they operate within the law, is to make as much money as possible.',
    directions: 'Write a response in which you discuss which view more closely aligns with your own position.',
    category: 'Corporate Responsibility',
  },
  {
    id: 82,
    accessCode: 'ISSUE082',
    prompt: 'Claim: Researchers should not limit their investigations to only those areas in which they expect to discover something that has an immediate, practical application.\nReason: It is impossible to predict the outcome of a line of research with any certainty.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'Pure vs Applied Research',
  },
  {
    id: 83,
    accessCode: 'ISSUE083',
    prompt: 'Some people believe that our ever-increasing use of technology significantly reduces our opportunities for human interaction. Other people believe that technology provides us with new and better ways to communicate and connect with one another.',
    directions: 'Write a response in which you discuss which view more closely aligns with your own position.',
    category: 'Technology & Connection',
  },
  {
    id: 84,
    accessCode: 'ISSUE084',
    prompt: 'Claim: Knowing about the past cannot help people to make important decisions today.\nReason: The world today is significantly more complex than it was even in the relatively recent past.',
    directions: 'Write a response in which you discuss the extent to which you agree or disagree with the claim and the reason on which that claim is based.',
    category: 'History & Modern Complexity',
  },
];
